# -*- coding: utf-8 -*-
"""Sample_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12K1u_C3GJhYWj-4sI07_cBS-cH_CTJO1
"""

!pip install cloudscraper
!pip install fake-useragent

import cloudscraper
import pandas as pd
from bs4 import BeautifulSoup
import time
import re
from datetime import datetime

import requests
from bs4 import BeautifulSoup
import time

# Initial UserAgent generator
ua = UserAgent()

REQUEST_DELAY = 4
REQUEST_TIMEOUT = 15

def clean_text(text):
    """Removes excess spaces and line breaks."""
    if not text:
        return ""
    text = re.sub(r"\s+", " ", str(text))
    return text.strip()

def normalise_campaign_url(url):
    """Takes the Kickstarter base URL."""
    url = url.split("?")[0].rstrip("/")
    suffixes = ["/description", "/rewards", "/creator", "/faqs", "/posts", "/comments", "/community"]
    for suffix in suffixes:
        if url.endswith(suffix):
            url = url[:-len(suffix)]
    return url

def scraped_time():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Optimize fetch page

# Scraper API, Because Keep On Giving 403 Error

SCRAPER_API_KEY = "d08cdd061b2c237dc5326112c3f521df"

def fetch_page(url):
    """
    Using Web Scraping API to bypass Colab IP block.
    """
    time.sleep(2)

    payload = {
        'api_key': SCRAPER_API_KEY,
        'url': url,
        'render': 'true'
    }

    try:
        response = requests.get('http://api.scraperapi.com', params=payload, timeout=60)
        status_code = response.status_code
        html = response.text

        print(f"URL: {url}")
        print(f"Status (from API): {status_code}")
        print(f"HTML length: {len(html)}")

        if status_code != 200:
            return status_code, html, None, f"API HTTP status {status_code}"

        soup = BeautifulSoup(html, "html.parser")
        return status_code, html, soup, None

    except Exception as error:
        return None, "", None, str(error)

# Content Extractors
def get_meta_content(soup, attribute_name):
    if soup is None: return ""
    tag = soup.find("meta", property=attribute_name)
    if tag and tag.get("content"):
        return clean_text(tag.get("content"))
    return ""

def remove_unwanted_tags(soup):
    if soup is None: return None
    for tag in soup.find_all(["script", "style", "noscript", "svg", "header", "footer", "nav", "form"]):
        tag.decompose()
    return soup

def extract_visible_text(soup):
    if soup is None: return ""
    soup_copy = BeautifulSoup(str(soup), "html.parser")
    soup_copy = remove_unwanted_tags(soup_copy)

    main_content = soup_copy.find("main")
    if main_content:
        return clean_text(main_content.get_text(" ", strip=True))

    body = soup_copy.find("body")
    if body:
        return clean_text(body.get_text(" ", strip=True))
    return ""

def extract_image_urls(soup):
    if soup is None: return []
    image_urls = []
    for img in soup.find_all("img"):
        image_url = img.get("src") or img.get("data-src")
        if image_url and image_url not in image_urls:
            image_urls.append(image_url)
    return image_urls

def extract_links_containing(soup, keyword):
    if soup is None: return []
    links = []
    for anchor in soup.find_all("a", href=True):
        href = anchor["href"]
        if keyword in href and href not in links:
            links.append(href)
    return links

def build_section_urls(campaign_url):
    base_url = normalise_campaign_url(campaign_url)
    return {
        "main_campaign": base_url,
        "story_description": f"{base_url}/description",
        "rewards": f"{base_url}/rewards",
        "creator": f"{base_url}/creator",
        "faq": f"{base_url}/faqs",
        "updates": f"{base_url}/posts",
        "comments": f"{base_url}/comments",
        "community": f"{base_url}/community"
    }

# Main Scraper

def scrape_one_campaign(campaign_url):
    base_url = normalise_campaign_url(campaign_url)
    section_urls = build_section_urls(base_url)

    result = {
        "campaign_url": base_url,
        "scraped_at": scraped_time()
    }

    all_image_urls = []

    for section_name, section_url in section_urls.items():
        print("\n" + "="*50)
        print(f"Testing section: {section_name}")

        status, html, soup, issue = fetch_page(section_url)

        visible_text = extract_visible_text(soup)
        image_urls = extract_image_urls(soup)

        result[f"{section_name}_url"] = section_url
        result[f"{section_name}_status"] = status
        result[f"{section_name}_issue"] = issue
        result[f"{section_name}_text"] = visible_text
        result[f"{section_name}_character_count"] = len(visible_text)
        result[f"{section_name}_image_count"] = len(image_urls)

        for image_url in image_urls:
            if image_url not in all_image_urls:
                all_image_urls.append(image_url)

        if section_name == "main_campaign" and soup:
            result["campaign_name"] = get_meta_content(soup, "og:title")
            result["blurb"] = get_meta_content(soup, "og:description")

        if section_name == "updates" and soup:
            result["possible_update_links"] = extract_links_containing(soup, "/posts/")

    result["all_image_urls"] = all_image_urls
    result["total_image_count"] = len(all_image_urls)

    return result


CAMPAIGN_URL = "https://www.kickstarter.com/projects/pophie/pophie-a-true-ai-lifeform"

sample_result = scrape_one_campaign(CAMPAIGN_URL)

sample_df = pd.DataFrame([sample_result])

status_cols = [col for col in sample_df.columns if col.endswith('_status') or col.endswith('_issue')]
sample_df[status_cols]